name: 🛡️ Website Scan Request
description: Submit a URL to scan for security and performance issues.
title: "[SCAN] <your-site-url>"
labels: [scan-request]
body:
  - type: markdown
    attributes:
      value: |
        Please enter the URL you’d like to scan. 
        - ZAP baseline security scan
        - is-website-vulnerable analysis
        - Lighthouse performance audit

  - type: input
    id: scan-url
    attributes:
      label: Website URL
      description: Must include http:// or https://
      placeholder: https://example.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ✅ Submit this form to trigger a scan. It may take a few minutes to complete. You’ll be notified via a comment once the reports are ready.
